# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-21 08:27:08
"""
import arcpy

def ImportingElephantMovementCoordinates():  # 1 Importing Elephant Movement Coordinates

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Conversion Tools.tbx")
    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"WGS_1984_UTM_Zone_35S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",27.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]", scratchWorkspace="V:\\859FinalProject_mhg29\\BassConnections_OrphanHotspots\\scratch"):
        Batoka_move_SubsetDry_Sept_Nov_xlsx = "V:\\859FinalProject_mhg29\\BassConnections_OrphanHotspots\\Data\\Orphan_Ele_Movement_Data\\Batoka_move_SubsetDry_Sept_Nov.xlsx"

        # Process: Excel To Table (Excel To Table) (conversion)
        Output_Table = "V:\\859FinalProject_mhg29\\BassConnections_OrphanHotspots\\scratch\\Batoka_move_SubsetDry_Sept_Nov_ExcelToTable2.dbf"
        arcpy.conversion.ExcelToTable(Input_Excel_File=Batoka_move_SubsetDry_Sept_Nov_xlsx, Output_Table=Output_Table)

        # Process: XY Table To Point (XY Table To Point) (management)
        EleMovementDataCombinedSubsetDry_ExcelToTable1_XYTableToPoint2_shp = "V:\\859FinalProject_mhg29\\BassConnections_OrphanHotspots\\scratch\\Batoka_move_SubsetDry_Sept_Nov_ExcelToTable2_XYTableToPoint1.shp"
        arcpy.management.XYTableToPoint(in_table=Output_Table, out_feature_class=EleMovementDataCombinedSubsetDry_ExcelToTable1_XYTableToPoint2_shp, x_field="Longitude", y_field="Latitude", coordinate_system="GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision")

        # Process: Project (Project) (management)
        Batoka_shp = "V:\\859FinalProject_mhg29\\BassConnections_OrphanHotspots\\Scratch\\Batoka.shp"
        arcpy.management.Project(in_dataset=EleMovementDataCombinedSubsetDry_ExcelToTable1_XYTableToPoint2_shp, out_dataset=Batoka_shp, out_coor_system="PROJCS[\"WGS_1984_UTM_Zone_35S\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",10000000.0],PARAMETER[\"Central_Meridian\",27.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(workspace="V:\\859FinalProject_mhg29\\BassConnections_OrphanHotspots\\Scratch"):
        ImportingElephantMovementCoordinates()
